spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}?autoReconnect=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
