name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: dynamically parse application.yml
        run: |
          cd ./src/main/resources
          sed 's/${DB_URL}/$DB_URL/g; s/${DB_PORT}/$DB_PORT/g; s/${DB_USERNAME}/$DB_USERNAME/g; s/${DB_PASSWORD}/$DB_PASSWORD/g;' application.yml > application.tmp.yml && mv application.tmp.yml application.yml
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}

      - name: test and build
        run:
          ./gradlew clean build --stacktrace
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}

      - name: run
        run:
          java -jar build/libs/educationLab-0.0.1-SNAPSHOT.jar
