name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  workflow:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
      - name: dynamically parse application.yml
        run: |
          cd ./src/main/resources
          sed 's/${DB_URL}/$DB_URL/g; s/${DB_PORT}/$DB_PORT/g; s/${DB_USERNAME}/$DB_USERNAME/g; s/${DB_PASSWORD}/$DB_PASSWORD/g;' application.yml > application.tmp.yml && mv application.tmp.yml application.yml
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}

      - name: test and build
        run:
          ./gradlew clean build --stacktrace

      - name: run
        run:
          java -jar build/libs/educationLab-0.0.1-SNAPSHOT.jar
